CREATE CACHED TABLE IF NOT EXISTS CONFIG_PARAM (
	NOMBRE varchar(65) NOT NULL PRIMARY KEY,
	TIPO integer NOT NULL,
	VALOR varchar(150) NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS GRUPO_CONSUMO (
	GRUPO_CONSUMO varchar(65) NOT NULL PRIMARY KEY,
	ABREVIATURA_CL varchar(2) NOT NULL,
	LABEL_CL varchar(65) NOT NULL
);

DROP INDEX IF EXISTS IDX_ABREVIATURA_GRP;
CREATE UNIQUE INDEX IF NOT EXISTS IDX_ABREVIATURA_GRP ON GRUPO_CONSUMO (ABREVIATURA_CL);

CREATE CACHED TABLE IF NOT EXISTS TIPO_CUENTA (
	TIPO_CUENTA varchar(45) NOT NULL PRIMARY KEY,
	ABREVIATURA_CL varchar(45) NOT NULL,
	LABEL_CL varchar(45) NOT NULL
);

CREATE CACHED TABLE IF NOT EXISTS CUENTA (
	CUENTA varchar(65) NOT NULL PRIMARY KEY,
	SALDO numeric(10, 2) NOT NULL,
	ABREVIATURA_CL varchar(2) NOT NULL,
	LABEL_CL varchar(65) NOT NULL,
	TIPO_CUENTA varchar(45) NOT NULL
);

DROP INDEX IF EXISTS IDX_ABREVIATURA_CTA;
CREATE UNIQUE INDEX IF NOT EXISTS IDX_ABREVIATURA_CTA ON CUENTA (ABREVIATURA_CL);

ALTER TABLE CUENTA DROP CONSTRAINT IF EXISTS FK_TIPO_CUENTA_CUENTA;
ALTER TABLE CUENTA ADD CONSTRAINT FK_TIPO_CUENTA_CUENTA FOREIGN KEY (TIPO_CUENTA) REFERENCES TIPO_CUENTA(TIPO_CUENTA) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE CACHED TABLE IF NOT EXISTS MOVIMIENTO (
	NRO_MOVIMIENTO integer auto_increment NOT NULL PRIMARY KEY,
	GRUPO_CONSUMO varchar(65) NOT NULL,
	FECHA date NOT NULL,
	CUENTA varchar(65) NOT NULL,
	PAGOS integer NOT NULL DEFAULT 1,
	IMPORTE numeric(10, 2) NOT NULL,
	IMPUTADO char(1) NOT NULL DEFAULT 'N',
	DESCRIPCION varchar(140) NOT NULL
);

ALTER TABLE MOVIMIENTO DROP CONSTRAINT IF EXISTS FK_MOVIMIENTO_GRP_CONSUMO;
ALTER TABLE MOVIMIENTO ADD CONSTRAINT FK_MOVIMIENTO_GRP_CONSUMO FOREIGN KEY (GRUPO_CONSUMO) REFERENCES GRUPO_CONSUMO(GRUPO_CONSUMO) ON DELETE RESTRICT ON UPDATE CASCADE;

ALTER TABLE MOVIMIENTO DROP CONSTRAINT IF EXISTS FK_MOVIMIENTO_CUENTA;
ALTER TABLE MOVIMIENTO ADD CONSTRAINT FK_MOVIMIENTO_CUENTA FOREIGN KEY (CUENTA) REFERENCES CUENTA(CUENTA) ON DELETE RESTRICT ON UPDATE CASCADE;

CREATE CACHED TABLE IF NOT EXISTS RESUMEN_TARJETA (
	NRO_RESUMEN integer AUTO_INCREMENT NOT NULL PRIMARY KEY,
	CUENTA varchar(65) NOT NULL,
	FECHA_VENCIMIENTO date,
	IMPORTE_TOTAL numeric(10, 2) NOT NULL,
	FECHA_CIERRE date,
	PAGADO char(1) NOT NULL
);

ALTER TABLE RESUMEN_TARJETA DROP CONSTRAINT IF EXISTS FK_CUENTA_RESUMEN;
ALTER TABLE RESUMEN_TARJETA ADD CONSTRAINT FK_CUENTA_RESUMEN FOREIGN KEY (CUENTA) REFERENCES CUENTA(CUENTA) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE CACHED TABLE IF NOT EXISTS MOVIMIENTO_RESUMEN (
	IMPORTE_PAGO numeric(10, 2) NOT NULL,
	NRO_MOVIMIENTO integer NOT NULL,
	NRO_RESUMEN integer NOT NULL,
	TEXTO_RESUMEN varchar(65) NOT NULL
);

ALTER TABLE MOVIMIENTO_RESUMEN DROP CONSTRAINT IF EXISTS FK_MOV_MOV_RES;
ALTER TABLE MOVIMIENTO_RESUMEN ADD CONSTRAINT FK_MOV_MOV_RES FOREIGN KEY (NRO_MOVIMIENTO) REFERENCES MOVIMIENTO(NRO_MOVIMIENTO) ON DELETE RESTRICT ON UPDATE RESTRICT;

ALTER TABLE MOVIMIENTO_RESUMEN DROP CONSTRAINT IF EXISTS FK_TARJETA_MOV_RESUMEN;
ALTER TABLE MOVIMIENTO_RESUMEN ADD CONSTRAINT FK_TARJETA_MOV_RESUMEN FOREIGN KEY (NRO_RESUMEN) REFERENCES RESUMEN_TARJETA(NRO_RESUMEN) ON DELETE NO ACTION ON UPDATE NO ACTION;

CREATE CACHED TABLE IF NOT EXISTS PLAZO_FIJO (
	NRO_PLAZO_FIJO integer AUTO_INCREMENT NOT NUll PRIMARY KEY, 
	BANCO varchar(65) NOT NULL,
	FECHA_VTO date NOT NULL,
	CAPITAL numeric(10, 2) NOT NULL,
	INTERES numeric(10, 2) NOT NULL,
	CERRADO char(1) NOT NULL
);
