INSERT INTO TIPO_CUENTA ( TIPO_CUENTA, ABREVIATURA_CL, LABEL_CL ) VALUES ( 'MOVIMIENTOS', 'MV', 'MOVIMIENTOS' );
INSERT INTO TIPO_CUENTA ( TIPO_CUENTA, ABREVIATURA_CL, LABEL_CL ) VALUES ( 'TARJETA CREDITO', 'TJ', 'TARJETA CREDITO' );
INSERT INTO TIPO_CUENTA ( TIPO_CUENTA, ABREVIATURA_CL, LABEL_CL ) VALUES ( 'PLAZO FIJO', 'PF', 'PLAZO FIJO' );
INSERT INTO CUENTA ( CUENTA, SALDO, ABREVIATURA_CL, LABEL_CL, TIPO_CUENTA ) VALUES ( 'PLAZOS FIJOS', 0, 'PF', 'PLAZO FIJO', 'PLAZO FIJO' );

